fix: fix synchronization with one drive - EXO-69480
exoplatform/cloud-drive-connectors pull request #22
Opened 2024-02-19 14:07 UTC by GouadriaHanen

this change upgrades the version of http3 to fix the synchronization with one drive

2024-02-19 14:33 UTC, rdenarie requested changes
Can you add more details in the commit message ? 
WHAT was the problem ? 
HOW do you fixed it ?
WHY theses modifications ?

2024-02-22 08:49 UTC, GouadriaHanen commented
> Can you add more details in the commit message ? WHAT was the problem ? HOW do you fixed it ? WHY theses modifications ?

description updated!

2024-02-22 10:45 UTC, rdenarie commented
The pr description is ok, but not the commit message.
Please change the commit message also

2024-02-22 12:13 UTC, GouadriaHanen commented
> The pr description is ok, but not the commit message. Please change the commit message also

done!

2024-02-22 12:35 UTC, rdenarie commented
Can you add the pr description in the commit message ? You only change the commit title 
![image](https://github.com/exoplatform/cloud-drive-connectors/assets/807839/5263dd80-1750-4a9e-bb26-e252a28d3887)

2024-02-22 14:23 UTC, GouadriaHanen commented
> Can you add the pr description in the commit message ? You only change the commit title ![image](https://private-user-images.githubusercontent.com/807839/306995750-5263dd80-1750-4a9e-bb26-e252a28d3887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDU2MzMsIm5iZiI6MTcwODYwNTMzMywicGF0aCI6Ii84MDc4MzkvMzA2OTk1NzUwLTUyNjNkZDgwLTE3NTAtNGE5ZS1iYjI2LWUyNTJhMjhkMzg4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMjM1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTQ4ODUyNTcyM2JmZTkyZjFjZWNhZjU2NmI2Y2FkZGE4NDgxNTk4NWQzYTY1NDc4NDgxNTBjMDMxYWVkNjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UQyW6-OI_21DSaopaOI0OIZGbQN6Pt28rd3CM4nzIn8)

done! but this used to be done when squashing and merging!

2024-02-22 14:45 UTC, rdenarie commented
It was to not forget it :)

2024-02-22 14:46 UTC, rdenarie approved these changes

2024-02-22 14:54 UTC, merged